stages:
  - test

cypress-run:
  stage: test
  image: cypress/browsers:node18.12.0-chrome107-ff107  # Cypress official docker image with browsers
  script:
    - npm ci            # clean install dependencies
    - npx cypress run --spec "cypress/e2e/Smoke/login.cy.js" --config-file cypress.config-prod.js -b chrome   # run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos  # save videos if test fails
      - cypress/screenshots  # save screenshots on errors
    expire_in: 1 week