stages:
  - test

cypress-run:
  stage: test
  image: cypress/browsers:22.12.0  # Cypress official docker image with browsers
  script:
    - npm ci  # clean install dependencies
    - npm start &
    - npx cypress run --spec "cypress/e2e/Smoke/login.cy.js" --config-file cypress.config-prod.js -b chrome  # run Cypress tests

  artifacts:
    when: always
    paths:
      - cypress/videos  # save videos if test fails
      - cypress/screenshots  # save screenshots on errors
    expire_in: 1 week