variables:
  ENV: stage
  SUITE_NAME: smoke 
stages:
  - test

cypress-run:
  stage: test
  image: cypress/browsers:22.12.0  # Cypress official docker image with browsers
  before_script:
    - apt-get update && apt-get install -y curl git
    - npm install
    - npm install js-yaml
  script:
    - eval $(node parse-suite.js)
    - echo $SUITES
    - echo $CONFIG_FILE
    - npm start &
    - npx cypress run --spec "$SUITES" --config-file "$CONFIG_FILE" -b chrome  # run Cypress tests
  rules:
    - when: manual
  artifacts:
    when: on_failure
    paths:
      - cypress/videos  # save videos if test fails
      - cypress/screenshots  # save screenshots on errors
    expire_in: 1 day