variables:
  TEST_SUITES:
    description: "Enter the suites name"
    value: "Smoke"
  CONFIG_FILE:
    description: "Please select rsepective config file"
    options:
      - "config-stage.yml"
      - "config-prod.yml"
stages:
  - test

cypress-run:
  stage: test
  image: alpine  # Cypress official docker image with browsers
  script:
    - npm ci            # clean install dependencies
    - npx cypress run --spec "cypress/e2e/Smoke/login.cy.js" --config-file cypress.config-prod.js -b chrome   # run Cypress tests
  artifacts:
    when: always
    paths:
      - cypress/videos  # save videos if test fails
      - cypress/screenshots  # save screenshots on errors
    expire_in: 1 week