name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      suite_name:
        description: 'Suite to run'
        required: true
        default: 'smokeUI'
        type: choice
        options:
          - SMOKE
          - smokeUI
          - API
      env:
        description: 'Environment to run'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - stage

env:
  ENV: ${{ github.event.inputs.env || 'prod' }}
  SUITE_NAME: ${{ github.event.inputs.suite_name || 'smokeUI' }}

jobs:
  smoke-ui:
    if: ${{ github.event.inputs.suite_name == 'smoke' || github.event.inputs.suite_name == 'smokeUI' }}
    name: Run Smoke UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install js-yaml

      - name: Parse suite
        id: parse
        run: |
          export SUITES='cypress/e2e/ui/**/*.cy.js'
          export CONFIG_FILE='cypress.config.js'
          echo "SUITES=$SUITES" >> $GITHUB_ENV
          echo "CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV

      - name: Start app
        run: npm start &

      - name: Run Cypress Smoke UI
        run: npx cypress run --spec "$SUITES" --config-file "$CONFIG_FILE" -b chrome

  smoke-api:
    if: ${{ github.event.inputs.suite_name == 'smoke' || github.event.inputs.suite_name == 'API' }}
    name: Run Smoke API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npm install js-yaml

      - name: Parse suite
        id: parse
        run: |
          export SUITES='cypress/e2e/api/**/*.cy.js'
          export CONFIG_FILE='cypress.config.api.js'
          echo "SUITES=$SUITES" >> $GITHUB_ENV
          echo "CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV

      - name: Run Cypress Smoke API
        run: npx cypress run --spec "$SUITES" --config-file "$CONFIG_FILE" -b chrome