kind: cypress
cypress:
  version:latest
  configFile: "cypress.config-stage.js"
rootDir: ./
suites:
 - name: "smoke"
    browser: "chrome"
    browserVersion: "latest"
    platformName: "Windows 10"
    screenResolution: "1920x1080"
    shard: spec
    config:
      specPattern: ["cypress\e2e\Smoke/*.js"]